include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - lib/**/*.g.dart
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    prefer_single_quotes: true