name: cookie
description: Client application for Discuit social platform.
publish_to: 'none'

version: 0.0.5+50

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # core
  intl: ^0.18.0
  http: ^1.1.0
  json_annotation: ^4.8.0
  json_serializable: ^6.7.1
  shared_preferences: ^2.2.0
  package_info_plus: ^4.0.0
  image: ^4.0.17

  # application
  auto_route: ^7.8.0
  provider: ^6.0.5
  url_launcher: ^6.1.11
  image_cropper: ^5.0.0
  image_picker: ^1.0.0

  # ui
  flash: ^3.0.5+1
  extended_image: ^8.1.0
  flutter_platform_widgets: ^6.0.2
  flutter_markdown: ^0.6.15+1
  markdown: ^7.1.0
  shimmer: ^3.0.0
  google_fonts: ^5.1.0
  cupertino_icons: ^1.0.2
  youtube_player_flutter: ^8.1.2

dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2
  auto_route_generator: ^7.3.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "launcher_icon_bg.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#616161"
  adaptive_icon_foreground: "launcher_icon.png"

flutter:
  generate: true
  uses-material-design: true
