name: "Build and release android application"
on:
  workflow_call:
    inputs:
      FLUTTER_VERSION:
        required: true
        type: string
      VERSION_TAG:  
        required: true
        type: string
    secrets:
      ANDROID_KEY_PROPERTIES:
        required: true
      ANDROID_KEY:  
        required: true
      
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3        
          
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11' 
        
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ inputs.FLUTTER_VERSION }}
          channel: 'stable'           
        
      - name: Init Android credentials files
        run: |
          echo "$ANDROID_KEY_PROPERTIES" > ./android/key.properties
          echo -n "$ANDROID_KEY" | base64 --decode > ./android/release.jks
        env:
          ANDROID_KEY_PROPERTIES: ${{ secrets.ANDROID_KEY_PROPERTIES }}
          ANDROID_KEY: ${{ secrets.ANDROID_KEY }}        

      - name: Build application
        run: |
          flutter pub get
          flutter build apk
          mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/cookie.apk
      
      - name: Upload apk
        uses: actions/upload-artifact@v3
        with:
          name: 'apk'
          path: build/app/outputs/flutter-apk/cookie.apk
          
      - name: Clean up
        if: always()
        run: |
          rm ./android/key.properties
          rm ./android/release.jks

  release:
    name: Release
    runs-on: ubuntu-latest

    needs: 
      - build
      
    steps: 
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 20
       
      - name: Get apk artifact
        uses: actions/download-artifact@v3
        with:
          name: 'apk'
          
#      - name: Get commits history
#        id: get_commits
#        uses: nrwl/nx-set-shas@v3
#        with:
#          last-successful-event: release
#
#      - name: Prepare changelog
#        id: generate_changelog
#        uses: mikepenz/release-changelog-builder-action@v3
#        with:
#          fromTag: ${{ steps.get_commits.outputs.base }}
#          toTag: ${{ steps.get_commits.outputs.head }}
#          commitMode: 'true'
#          configuration: 'changelog_config.json'
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ inputs.VERSION_TAG }}
#          body: ${{ steps.generate_changelog.outputs.changelog }}
          files: cookie.apk
          prerelease: true

